version: '3.9'

services:
  django:
    container_name: schedule_app
    build: 
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8001:8000
